iso21378abbrev = {
  "ACC": "Account",
  "ADCS": "Audit Data Collection Standard",
  "ADJ": "Adjustment",
  "AP": "Accounts Payable",
  "AR": "Accounts Receivable",
  "ASCII": "American Standard Code for Information Interchange",
  "BAS": "Base",
  "BEG": "Beginning",
  "BIC": "Business Identifier Code",
  "CFO": "Chief Financial Officer",
  "CNY": "Chinese Yuan",
  "CRLF": "Carriage-Return Line-Feed",
  "CSV": "Comma Separated Values",
  "CUR": "Currency",
  "CUS": "Customer",
  "ERM": "Enterprise Resource Management",
  "ERP": "Enterprise Resource Planning",
  "EUR": "Euro",
  "FIFO": "First In, First Out",
  "FOB": "Free On Board",
  "FS": "Financial Statement",
  "GB": "Gigabyte",
  "GL": "General Ledger",
  "IBAN": "International Bank Account Number",
  "ICBC": "Industrial and Commercial Bank of China",
  "ID": "Identification",
  "INV": "Inventory",
  "IT": "Information Technology",
  "JE": "Journal Entry",
  "LEI": "Legal Entity Identifier",
  "LIFO": "Last In, First Out",
  "MS-DOS": "Microsoft Disk Operating System",
  "NTFS": "New Technology File System",
  "NUM": "Number",
  "NY": "New York State",
  "ORG": "Organization",
  "OS": "Operating System",
  "PK": "Primary Key",
  "PO": "Purchase Order",
  "PPE": "Property, Plant and Equipment",
  "PRV": "Province",
  "PUR": "Purchase",
  "REF": "Reference Identifier",
  "RFC": "Request For Comments",
  "SAL": "Sales",
  "SAP": "Systems Applications and Products in data processing",
  "SQL": "Structured Query Language",
  "TB": "Terabytes",
  "TIN": "Tax Identification Number",
  "TRX": "Transactional",
  "UOM": "Unit of Measurement",
  "US": "United States of America",
  "USD": "U.S. Dollars",
  "UTC": "Coordinated Universal Time",
  "UTF-8": "8-bit Unicode Transformation Format",
  "WIP": "Work In Progress"
}
abbreviation = {
  "8-bit Unicode Transformation Format": "UTF-8",
  "Abbreviation": "Abrv",
  "Academic": "Acad",
  "Account": "Acnt",
  "Account": "Acc",
  "Accounts Payable": "Ap",
  "Accounts Receivable": "Ar",
  "Accrual": "Accrl",
  "Accumulated": "Accum",
  "Acquisition": "Acq",
  "Addition": "Add",
  "Address": "Adr",
  "Adjusted": "Adjd",
  "Adjustment": "Adj",
  "Adjustment": "ADJ",
  "After": "Aft",
  "Allocation": "Alloc",
  "American Standard Code for Information Interchange": "Ascii",
  "Amount": "Amt",
  "Application": "Apl",
  "Approved": "Aprv",
  "AR": "Ar",
  "Audit Data Collection Standard": "Adcs",
  "Balance": "Bal",
  "BAS": "Bas",
  "Base": "Bas",
  "Before": "Bef",
  "Beginning": "Beg",
  "Beginning": "Beg",
  "Billing": "Bill",
  "Branch": "Bra",
  "Business Identifier Code": "Bic",
  "Business": "Bus",
  "Cancellation": "Cncl",
  "Carriage-Return Line-Feed": "CRLF",
  "Change": "Chng",
  "Chief Financial Officer": "Cfo",
  "Chinese Yuan": "Cny",
  "Code": "Cd",
  "Comma Separated Values": "Csv",
  "Contact": "Cnt",
  "Content": "Cont",
  "Contract": "Contr",
  "Coordinated Universal Time": "Utc",
  "Corresponding": "Corr",
  "Costing": "Cstng",
  "Country": "Cntry",
  "Created": "Crea",
  "Credit": "Cr",
  "Currency": "Cur",
  "Currency": "Cur",
  "Customer": "Cust",
  "Customer": "Cus",
  "Customized": "Cstmzd",
  "Date": "Dt",
  "Debit": "Db",
  "Default": "Dft",
  "Department": "Dep",
  "Depreciable": "Dprcbl",
  "Depreciation": "Depre",
  "Description": "Dscr",
  "Details": "Dtls",
  "Developer": "Dvlpr",
  "Discount": "Dscnt",
  "Dispatch": "Disp",
  "Document": "Doc",
  "Employee": "Emp",
  "Employment": "Emplmnt",
  "Encoding": "Enc",
  "Ending": "End",
  "Enterprise Resource Management": "Erm",
  "Enterprise Resource Planning": "Erp",
  "Euro": "Eur",
  "Exclude": "Excl",
  "Expense": "Expns",
  "External": "Ext",
  "Financial Statement": "Fs",
  "First In, First Out": "Fifo",
  "Fiscal": "Fisc",
  "Fiscal": "Fscl",
  "Free On Board": "Fob",
  "Functional": "Func",
  "General Ledger": "Gl",
  "Generated": "Gen",
  "Gigabyte": "GB",
  "GL": "Gl",
  "Grouping": "Grp",
  "Header": "Hdr",
  "Hierarchy": "Hrchy",
  "Identification": "Id",
  "Identifier": "Id",
  "Impairment": "Impr",
  "Include": "Incl",
  "Indicator": "Ind",
  "Industrial and Commercial Bank of China": "Icbc",
  "Information Technology": "IT",
  "International Bank Account Number": "Iban",
  "Inventory": "Inv",
  "Inventory": "Inv",
  "Invoice": "Invoi",
  "Journal Entry": "Je",
  "Journal": "Jrn",
  "Last In, First Out": "Lifo",
  "Last": "Lst",
  "Legal Entity Identifier": "Lei",
  "Line": "Ln",
  "List": "Lst",
  "Local": "Loc",
  "Location": "Lct",
  "Materials": "Mat",
  "Measurement": "Mea",
  "Method": "Mthd",
  "Microsoft Disk Operating System": "MS-DOS",
  "Modified": "Mdf",
  "Module": "Mod",
  "Name": "Nm",
  "New Technology File System": "Ntfs",
  "New York State": "Ny",
  "Number": "Nr",
  "Number": "Num",
  "Open": "Opn",
  "Operating System": "Os",
  "Order": "Ord",
  "Organization": "Org",
  "Parent": "Par",
  "Payable": "Pbl",
  "Payment": "Pay",
  "Percentage": "Perc",
  "Period": "Per",
  "Person": "Prsn",
  "Physical": "Phys",
  "Primary Key": "Pk",
  "Primary": "Prim",
  "Proceeds": "Prcds",
  "Process": "Proc",
  "Product": "Prdct",
  "Project": "Proj",
  "Property, Plant and Equipment": "Ppe",
  "Proportion": "Prop",
  "Province": "Prvnc",
  "Province": "PRV",
  "Provision": "Prov",
  "Purchase Order": "Po",
  "Purchase": "Pur",
  "Purchase": "PUR",
  "Purchasing": "Prchsng",
  "Quantity": "Qt",
  "Realized": "Rlzd",
  "Receipt": "Rcpt",
  "Receivable": "Rcvbl",
  "Received": "Rcvd",
  "Records": "Rec",
  "Reference Identifier": "Ref",
  "Reference": "Ref",
  "Regulator": "Rgltr",
  "Remaining": "Rmng",
  "Remark": "Rmrk",
  "Removal": "Rmv",
  "Replacemant": "Replac",
  "Replacement": "Rplc",
  "Reporting": "Rprt",
  "Request For Comments": "Rfc",
  "Requisition": "Rqstn",
  "Residual": "Resi",
  "Responsibility": "Resp",
  "Reversal": "Rev",
  "Sales": "Sal",
  "Segment": "Sg",
  "Service": "Srvc",
  "Settlement": "Setl",
  "Sheet": "Sht",
  "Shipment": "Shp",
  "Shipping": "Shpng",
  "Software": "Sftw",
  "Source": "Src",
  "Standard": "Std",
  "Status": "Stat",
  "Stocking": "Stck",
  "Structured Query Language": "Sql",
  "Subledger": "Sbldgr",
  "Supplier": "Supl",
  "System": "Syst",
  "Systems Applications and Products in data processing": "Sap",
  "Tax Identification Number": "Tin",
  "Terabytes": "Tb",
  "Terms": "Trms",
  "Time": "Tm",
  "Total": "Tot",
  "Transaction": "Tr",
  "Transactional": "Trx",
  "Type": "Typ",
  "U.S. Dollars": "Usd",
  "Unit of Measurement": "Uom",
  "United States of America": "Us",
  "Unrealized": "Unrlzd",
  "Version": "Vers",
  "Work In Progress": "Wip",
  "Year": "Yr",
}